### ISSUE TITLE
Requirement controls button is broken

### ISSUE THREAD

**Issue by xchatiii** [rextse04/credit-planner#13]
All buttons (add task, add xxx group, delete) in group requirements are broken.

Expected behavior:
All buttons add tasks, groups and deletes as usual.

Actual bevahior:
The add task button and add xxx group buttons do not add anything, and the delete group button deletes the previous requirement entry instead.

**Comment by rextse04** [comment]
Fixed🤗

**Comment by rextse04** [comment]
Fixed🤗
