### ISSUE TITLE
[bug] Minimum courses requirement does not work as expected

### ISSUE THREAD

**Issue by xchatiii** [rextse04/credit-planner#15]
In [issue.json](https://github.com/user-attachments/files/15535240/issue.json), although there are already 4 courses satisfying the requirement, the 4 minimum courses requirement in the outer OR bracket is shown to be not satisfied (although the minimum credit requirement is satisfied).

**Comment by rextse04** [comment]
Fixed*. Technically, this is _a feature, not a bug_, because I defined min. courses as the number of satisfied requirement blocks in the block. However, this definition is probably not what users would expect and is not very useful, so I have decided to change its behaviour.
