### ISSUE TITLE
Check require multiple iterations

### ISSUE THREAD

**Issue by xchatiii** [rextse04/credit-planner#6]
The check button needs multiple presses until all requirements are checked correctly.

Expected behavior:
Pressing the check button once immediately gives correct results

Actual behavior:
For each press, only the innermost group is checked. The next press checks the second innermost group, thus needing multiple presses for a correct result.

**Comment by rextse04** [comment]
I cannot reproduce the issue. Can you export your plan and upload the file? Screenshots also work.

**Comment by xchatiii** [comment]
Initial
![i](https://github.com/rextse04/credit-planner/assets/69412273/10914254-0ee6-443b-93c8-b52fd1baf423)

1st click
![1](https://github.com/rextse04/credit-planner/assets/69412273/28e5f97a-3764-48b4-9d39-e72f868cf5d2)

2nd click
![2](https://github.com/rextse04/credit-planner/assets/69412273/8148a4d3-f490-48af-91c2-2f276e99eb36)

3rd click
![3](https://github.com/rextse04/credit-planner/assets/69412273/416c2f48-e0d6-4a8d-978c-ff4877bf1db8)

Needs at least three checks to be correct.

**Comment by rextse04** [comment]
Hm...Can you send the file?🤡

**Comment by xchatiii** [comment]
[My Plan.json](https://github.com/rextse04/credit-planner/files/14072499/My.Plan.json)

**Comment by xchatiii** [comment]
...did I just import that and made the whole thing crash? Here eat this issue https://github.com/rextse04/credit-planner/issues/12

**Comment by rextse04** [comment]
Fixed, with great effort🙃

**Comment by rextse04** [comment]
Fixed, with great effort🙃
